theme = "minimalist"
baseurl = "http://chaseadams.io"
languageCode = "en-us"
title = "Chase Adams"

topic = "topics"

[params]
  tagline = "intentional input Â» effective output"
  description = "I'm Chase Adams. Engineer at Walmart Labs. Life Learner. Programming Polyglot."
  author = "Chase Adams"
  dns = "digital ocean"
  gaid = "UA-62564031-1"

[permalinks]
  articles = "/:slug/"
  archive = "/:slug/"
  page = "/:filename/"

[[menu.main]]
  name = "Start Here"
  weight = -110
  url = "/about"
[[menu.main]]
  name = "Blog"
  weight = 110
  url = "/articles"
[[menu.main]]
  name = "Archive"
  weight = 210
  url = "/archive"
